export const actionTypes = {

  MAIN_NAV_START_FETCHING: 'MAIN_NAV_START_FETCHING',
  MAIN_NAV_FETCHED: 'MAIN_NAV_FETCHED',
  MAIN_NAV_FETCH_ERROR: 'MAIN_NAV_FETCH_ERROR',

  HOME_START_FETCHING: 'HOME_START_FETCHING',
  HOME_FETCHED: 'HOME_FETCHED',
  HOME_FETCH_ERROR: 'HOME_FETCH_ERROR',

  ABOUT_START_FETCHING: 'ABOUT_START_FETCHING',
  ABOUT_FETCHED: 'ABOUT_FETCHED',
  ABOUT_FETCH_ERROR: 'ABOUT_FETCH_ERROR',

  FOOD_MENU_START_FETCHING: 'FOOD_MENU_START_FETCHING',
  FOOD_MENU_FETCHED: 'FOOD_MENU_FETCHED',
  FOOD_MENU_FETCH_ERROR: 'FOOD_MENU_FETCH_ERROR',

  FOOD_MENU_TXN_TERM_START_FETCHING: 'FOOD_MENU_TXN_TERM_START_FETCHING',
  FOOD_MENU_TXN_TERM_FETCHED: 'FOOD_MENU_TXN_TERM_FETCHED',
  FOOD_MENU_TXN_TERM_FETCH_ERROR: 'FOOD_MENU_TXN_TERM_FETCH_ERROR',

  FOOD_MENU_BG_START_FETCHING: 'FOOD_MENU_BG_START_FETCHING',
  FOOD_MENU_BG_FETCHED: 'FOOD_MENU_BG_FETCHED',
  FOOD_MENU_BG_FETCH_ERROR: 'FOOD_MENU_BG_FETCH_ERROR',

}